name: smartnote_env
channels:
  - defaults
dependencies:
  - python=3.9.13
  - pip:
    - pip
    - langchain==0.1.0
    - langchain-community==0.0.17
    - langchain-core==0.1.18
    - langchain-openai==0.0.5
    - langcodes==3.3.0
    - langdetect==1.0.9
    - langsmith==0.0.86
    - pytest==8.0.0
    - python-dotenv~=1.0.0
    - openai
    - google-api-python-client
    - google-search-results
    - youtube-transcript-api
    - chromadb
    - tiktoken
    - faiss-cpu
    - wikipedia
    - psycopg2-binary
    - pinecone-client
    - pgvector
    - nltk~=3.8.1
    - PyPDF2
    - PyPDF
