on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    # Checkout the code
    - uses: actions/checkout@v4

    # Set up JDK 17
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        architecture: 'x64'

    # Set up Ivy
    - run: |
        wget https://dlcdn.apache.org//ant/ivy/2.5.2/apache-ivy-2.5.2-bin.tar.gz
        tar -xzf apache-ivy-2.5.2-bin.tar.gz
        mv apache-ivy-2.5.2/ivy-2.5.2.jar /home/runner/.ant/lib/

    # Resolve the dependencies
    - run: ant -noinput -buildfile server/build.xml resolve

    # Build the project
    - run: ant -noinput -buildfile server/build.xml build-test

    # Run the tests
    - run: ant -noinput -buildfile server/build.xml test

    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          server/test-results/**/*.xml
          server/test-results/**/*.trx
          server/test-results/**/*.json

